export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const DASHBOARD_FAILURE = "DASHBOARD_FAILURE";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";

export const RATION_SUCCESS = "RATION_SUCCESS";
export const RATION_FALIURE = "RATION_FALIURE";

export const GENDER_SUCCESS = "GENDER_SUCCESS";
export const GENDER_FALIURE = "GENDER_FALIURE";


export const ECONOMIC_CATEGORIES_SUCCESS = "ECONOMIC_CATEGORIES_SUCCESS";
export const ECONOMIC_CATEGORIES_FALIURE = "ECONOMIC_CATEGORIES_FALIURE";

export const RESIDENTIAL_SUCCESS = "RESIDENTIAL_SUCCESS";
export const RESIDENTIAL_FALIURE = "RESIDENTIAL_FALIURE";

export const RELATION_SUCCESS = "RELATION_SUCCESS";
export const RELATION_FALIURE = "RELATION_FALIURE";


export const QUALIFICATION_SUCCESS = "QUALIFICATION_SUCCESS";
export const QUALIFICATION_FALIURE = "QUALIFICATION_FALIURE";


export const OCCUPATION_SUCCESS = "OCCUPATION_SUCCESS";
export const OCCUPATION_FALIURE = "OCCUPATION_FALIURE";

export const SET_VALUE = "SET_VALUE";
export const SET_VALUE_ERROR = "SET_VALUE_ERROR";


export const RELIGION_SUCCESS = "RELIGION_SUCCESS";
export const RELIGION_FALIURE = "RELIGION_FALIURE";

export const SOCIAL_CAT_SUCCESS = "SOCIAL_CAT_SUCCESS";
export const SOCIAL_CAT_FALIURE = "SOCIAL_CAT_FALIURE";

export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_FALIURE = "DISTRICT_FALIURE";


export const MUNICIPALITY_SUCCESS = "MUNICIPALITY_SUCCESS";
export const MUNICIPALITY_FALIURE = "MUNICIPALITY_FALIURE";


export const WARD_SUCCESS = "WARD_SUCCESS";
export const WARD_FALIURE = "WARD_FALIURE";


export const FAMILY_DETAIL_SUCCESS = "FAMILY_DETAIL_SUCCESS";
export const FAMILY_DETAIL_FALIURE = "FAMILY_DETAIL_FALIURE";


export const FAMILIES_LIST_SUCCESS = "FAMILIES_LIST_SUCCESS";
export const FAMILIES_LIST_FALIURE = "FAMILIES_LIST_FALIURE";


export const FAMILIES_DETAIL_SUCCESS = "FAMILIES_DETAIL_SUCCESS";
export const FAMILIES_DETAIL_FALIURE = "FAMILIES_DETAIL_FALIURE";


export const SHOW_LOADER_SUCCESS = "SHOW_LOADER_SUCCESS";
export const SHOW_LOADER_FALIURE = "SHOW_LOADER_FALIURE";
